### ISSUE TITLE
troubles upgrading to 0.17.0

### ISSUE THREAD

**Issue by hjanuschka** [kriswallsmith/Buzz#315]
hey 🤚 

we are in the progress to upgrade to `0.17.0`

the following issues have arrived:

```
use Buzz\Message\Response as BuzzResponse;
```

not found, can be fixed with:

```
use Nyholm\Psr7\Response as BuzzResponse;
```

is that correct ❓ 

the bigger one is: 
in our symfony app we have the following:

```yaml
    krn_bridge.browser.client.curl:
        class: Buzz\Client\Curl
        public: false
        calls:
          - [setTimeout , ["%krn_bridge.client_timeout%"]]

    krn_bridge.browser:
        class: KRN\BridgeBundle\Services\KrnBridgeBrowser
        public: false
        arguments: ["@krn_bridge.browser.client.curl"]
 ```

the method `setTimeout` has been removed, and we currently have no clou how to provide options
can you help me with this one?

using `krn_bridge.browser`  with e.g: `$browser->get()`
